import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── Stitch Design System Tokens ──────────────────
        primary: "#4648d4",
        "primary-container": "#6063ee",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-primary-fixed": "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        secondary: "#575e70",
        "secondary-container": "#d9dff5",
        "secondary-fixed": "#dce2f7",
        "secondary-fixed-dim": "#c0c6db",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5c6274",
        "on-secondary-fixed": "#141b2b",
        "on-secondary-fixed-variant": "#404758",
        tertiary: "#5a5c5d",
        "tertiary-container": "#737576",
        "tertiary-fixed": "#e1e3e4",
        "tertiary-fixed-dim": "#c5c7c8",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fcfdfe",
        "on-tertiary-fixed": "#191c1d",
        "on-tertiary-fixed-variant": "#454748",
        surface: "#f9f9ff",
        "surface-dim": "#d3daea",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eefe",
        "surface-container-high": "#e2e8f8",
        "surface-container-highest": "#dce2f3",
        "surface-variant": "#dce2f3",
        "surface-tint": "#494bd6",
        "on-surface": "#151c27",
        "on-surface-variant": "#464554",
        "inverse-surface": "#2a313d",
        "inverse-on-surface": "#ebf1ff",
        "inverse-primary": "#c0c1ff",
        background: "#f9f9ff",
        "on-background": "#151c27",
        outline: "#767586",
        "outline-variant": "#c7c4d7",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        // ── Semantic ─────────────────────────────────────
        success: "#10B981",
        warning: "#F59E0B",
        danger: "#EF4444",
        info: "#3B82F6",
        // ── Status Badges ─────────────────────────────────
        "status-new-bg": "#EFF6FF",
        "status-new-text": "#1D4ED8",
        "status-contacted-bg": "#FFF7ED",
        "status-contacted-text": "#C2410C",
        "status-qualified-bg": "#F0FDF4",
        "status-qualified-text": "#15803D",
        "status-proposal-bg": "#FAF5FF",
        "status-proposal-text": "#7E22CE",
        "status-won-bg": "#F0FDF4",
        "status-won-text": "#166534",
        "status-lost-bg": "#FEF2F2",
        "status-lost-text": "#991B1B",
      },
      borderRadius: {
        DEFAULT: "0.25rem", // matches Stitch rounded (4px)
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem", // matches Stitch rounded-lg (8px)
        xl: "0.75rem", // matches Stitch rounded-xl (12px)
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "240px",
        gutter: "1.5rem",
        "margin-mobile": "1rem",
        "margin-desktop": "2rem",
        "stack-sm": "0.5rem",
        "stack-md": "1rem",
        "stack-lg": "1.5rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        // Stitch font-family aliases
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "mono-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "20px",
          { lineHeight: "28px", fontWeight: "700" },
        ],
        "headline-md": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "mono-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
      boxShadow: {
        card: "0 2px 10px rgba(0,0,0,0.04)",
        modal: "0 20px 48px rgba(0,0,0,0.16)",
        header: "0 1px 3px rgba(0,0,0,0.06)",
      },
      animation: {
        "fade-in": "fadeIn 0.2s ease-out",
        "slide-up": "slideUp 0.3s ease-out",
        "count-up": "countUp 1.2s ease-out",
      },
      keyframes: {
        fadeIn: { from: { opacity: "0" }, to: { opacity: "1" } },
        slideUp: {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
